# Generated by Django 5.2.7 on 2025-10-15 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_is_admin_usuario_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('superuser', 'Superusuario'), ('profesor', 'Profesor')], default='profesor', max_length=20),
        ),
    ]
