apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authservice-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/UDLAIA-STATS/authservice.git
    targetRevision: main
    path: prod
  destination:
    server: https://kubernetes.default.svc
    namespace: authservice-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
